# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ORB_SERVER/clientBag.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import ORB_SERVER.msg
import sensor_msgs.msg

class clientBag(genpy.Message):
  _md5sum = "d2ff93391b125645f1b1afd51415dde4"
  _type = "ORB_SERVER/clientBag"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """keypoint[] keyPoints
sensor_msgs/Image descriptors

uint32 rows
uint32 cols
uint32 nKeypoints
uint64 nNextId
uint64 mnId

float64[] imuTimestamp
gyroscope[] gyr
accleration[] acc 

float64 sendTimestamp


================================================================================
MSG: ORB_SERVER/keypoint
float32 ptx
float32 pty
float32 size
float32 angle
float32 response
int8 octave
int8 class_id

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of cameara
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: ORB_SERVER/gyroscope
float64 gyrx
float64 gyry
float64 gyrz

================================================================================
MSG: ORB_SERVER/accleration
float64 accx
float64 accy
float64 accz
"""
  __slots__ = ['keyPoints','descriptors','rows','cols','nKeypoints','nNextId','mnId','imuTimestamp','gyr','acc','sendTimestamp']
  _slot_types = ['ORB_SERVER/keypoint[]','sensor_msgs/Image','uint32','uint32','uint32','uint64','uint64','float64[]','ORB_SERVER/gyroscope[]','ORB_SERVER/accleration[]','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       keyPoints,descriptors,rows,cols,nKeypoints,nNextId,mnId,imuTimestamp,gyr,acc,sendTimestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(clientBag, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.keyPoints is None:
        self.keyPoints = []
      if self.descriptors is None:
        self.descriptors = sensor_msgs.msg.Image()
      if self.rows is None:
        self.rows = 0
      if self.cols is None:
        self.cols = 0
      if self.nKeypoints is None:
        self.nKeypoints = 0
      if self.nNextId is None:
        self.nNextId = 0
      if self.mnId is None:
        self.mnId = 0
      if self.imuTimestamp is None:
        self.imuTimestamp = []
      if self.gyr is None:
        self.gyr = []
      if self.acc is None:
        self.acc = []
      if self.sendTimestamp is None:
        self.sendTimestamp = 0.
    else:
      self.keyPoints = []
      self.descriptors = sensor_msgs.msg.Image()
      self.rows = 0
      self.cols = 0
      self.nKeypoints = 0
      self.nNextId = 0
      self.mnId = 0
      self.imuTimestamp = []
      self.gyr = []
      self.acc = []
      self.sendTimestamp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.keyPoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.keyPoints:
        _x = val1
        buff.write(_struct_5f2b.pack(_x.ptx, _x.pty, _x.size, _x.angle, _x.response, _x.octave, _x.class_id))
      _x = self
      buff.write(_struct_3I.pack(_x.descriptors.header.seq, _x.descriptors.header.stamp.secs, _x.descriptors.header.stamp.nsecs))
      _x = self.descriptors.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.descriptors.height, _x.descriptors.width))
      _x = self.descriptors.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.descriptors.is_bigendian, _x.descriptors.step))
      _x = self.descriptors.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I2Q.pack(_x.rows, _x.cols, _x.nKeypoints, _x.nNextId, _x.mnId))
      length = len(self.imuTimestamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.imuTimestamp))
      length = len(self.gyr)
      buff.write(_struct_I.pack(length))
      for val1 in self.gyr:
        _x = val1
        buff.write(_struct_3d.pack(_x.gyrx, _x.gyry, _x.gyrz))
      length = len(self.acc)
      buff.write(_struct_I.pack(length))
      for val1 in self.acc:
        _x = val1
        buff.write(_struct_3d.pack(_x.accx, _x.accy, _x.accz))
      buff.write(_struct_d.pack(self.sendTimestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.keyPoints is None:
        self.keyPoints = None
      if self.descriptors is None:
        self.descriptors = sensor_msgs.msg.Image()
      if self.gyr is None:
        self.gyr = None
      if self.acc is None:
        self.acc = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.keyPoints = []
      for i in range(0, length):
        val1 = ORB_SERVER.msg.keypoint()
        _x = val1
        start = end
        end += 22
        (_x.ptx, _x.pty, _x.size, _x.angle, _x.response, _x.octave, _x.class_id,) = _struct_5f2b.unpack(str[start:end])
        self.keyPoints.append(val1)
      _x = self
      start = end
      end += 12
      (_x.descriptors.header.seq, _x.descriptors.header.stamp.secs, _x.descriptors.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.descriptors.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.descriptors.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.descriptors.height, _x.descriptors.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.descriptors.encoding = str[start:end].decode('utf-8')
      else:
        self.descriptors.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.descriptors.is_bigendian, _x.descriptors.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.descriptors.data = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.rows, _x.cols, _x.nKeypoints, _x.nNextId, _x.mnId,) = _struct_3I2Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.imuTimestamp = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gyr = []
      for i in range(0, length):
        val1 = ORB_SERVER.msg.gyroscope()
        _x = val1
        start = end
        end += 24
        (_x.gyrx, _x.gyry, _x.gyrz,) = _struct_3d.unpack(str[start:end])
        self.gyr.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.acc = []
      for i in range(0, length):
        val1 = ORB_SERVER.msg.accleration()
        _x = val1
        start = end
        end += 24
        (_x.accx, _x.accy, _x.accz,) = _struct_3d.unpack(str[start:end])
        self.acc.append(val1)
      start = end
      end += 8
      (self.sendTimestamp,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.keyPoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.keyPoints:
        _x = val1
        buff.write(_struct_5f2b.pack(_x.ptx, _x.pty, _x.size, _x.angle, _x.response, _x.octave, _x.class_id))
      _x = self
      buff.write(_struct_3I.pack(_x.descriptors.header.seq, _x.descriptors.header.stamp.secs, _x.descriptors.header.stamp.nsecs))
      _x = self.descriptors.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.descriptors.height, _x.descriptors.width))
      _x = self.descriptors.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.descriptors.is_bigendian, _x.descriptors.step))
      _x = self.descriptors.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I2Q.pack(_x.rows, _x.cols, _x.nKeypoints, _x.nNextId, _x.mnId))
      length = len(self.imuTimestamp)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.imuTimestamp.tostring())
      length = len(self.gyr)
      buff.write(_struct_I.pack(length))
      for val1 in self.gyr:
        _x = val1
        buff.write(_struct_3d.pack(_x.gyrx, _x.gyry, _x.gyrz))
      length = len(self.acc)
      buff.write(_struct_I.pack(length))
      for val1 in self.acc:
        _x = val1
        buff.write(_struct_3d.pack(_x.accx, _x.accy, _x.accz))
      buff.write(_struct_d.pack(self.sendTimestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.keyPoints is None:
        self.keyPoints = None
      if self.descriptors is None:
        self.descriptors = sensor_msgs.msg.Image()
      if self.gyr is None:
        self.gyr = None
      if self.acc is None:
        self.acc = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.keyPoints = []
      for i in range(0, length):
        val1 = ORB_SERVER.msg.keypoint()
        _x = val1
        start = end
        end += 22
        (_x.ptx, _x.pty, _x.size, _x.angle, _x.response, _x.octave, _x.class_id,) = _struct_5f2b.unpack(str[start:end])
        self.keyPoints.append(val1)
      _x = self
      start = end
      end += 12
      (_x.descriptors.header.seq, _x.descriptors.header.stamp.secs, _x.descriptors.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.descriptors.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.descriptors.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.descriptors.height, _x.descriptors.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.descriptors.encoding = str[start:end].decode('utf-8')
      else:
        self.descriptors.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.descriptors.is_bigendian, _x.descriptors.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.descriptors.data = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.rows, _x.cols, _x.nKeypoints, _x.nNextId, _x.mnId,) = _struct_3I2Q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.imuTimestamp = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.gyr = []
      for i in range(0, length):
        val1 = ORB_SERVER.msg.gyroscope()
        _x = val1
        start = end
        end += 24
        (_x.gyrx, _x.gyry, _x.gyrz,) = _struct_3d.unpack(str[start:end])
        self.gyr.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.acc = []
      for i in range(0, length):
        val1 = ORB_SERVER.msg.accleration()
        _x = val1
        start = end
        end += 24
        (_x.accx, _x.accy, _x.accz,) = _struct_3d.unpack(str[start:end])
        self.acc.append(val1)
      start = end
      end += 8
      (self.sendTimestamp,) = _struct_d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d = struct.Struct("<d")
_struct_BI = struct.Struct("<BI")
_struct_5f2b = struct.Struct("<5f2b")
_struct_3I = struct.Struct("<3I")
_struct_3I2Q = struct.Struct("<3I2Q")
_struct_2I = struct.Struct("<2I")
_struct_3d = struct.Struct("<3d")
