/* Auto-generated by genmsg_cpp for file /home/chiao/documents/serverRobot/ORB_SERVER/msg/gyroscope.msg */
#ifndef ORB_SERVER_MESSAGE_GYROSCOPE_H
#define ORB_SERVER_MESSAGE_GYROSCOPE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ORB_SERVER
{
template <class ContainerAllocator>
struct gyroscope_ {
  typedef gyroscope_<ContainerAllocator> Type;

  gyroscope_()
  : gyrx(0.0)
  , gyry(0.0)
  , gyrz(0.0)
  {
  }

  gyroscope_(const ContainerAllocator& _alloc)
  : gyrx(0.0)
  , gyry(0.0)
  , gyrz(0.0)
  {
  }

  typedef double _gyrx_type;
  double gyrx;

  typedef double _gyry_type;
  double gyry;

  typedef double _gyrz_type;
  double gyrz;


  typedef boost::shared_ptr< ::ORB_SERVER::gyroscope_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ORB_SERVER::gyroscope_<ContainerAllocator>  const> ConstPtr;
}; // struct gyroscope
typedef  ::ORB_SERVER::gyroscope_<std::allocator<void> > gyroscope;

typedef boost::shared_ptr< ::ORB_SERVER::gyroscope> gyroscopePtr;
typedef boost::shared_ptr< ::ORB_SERVER::gyroscope const> gyroscopeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ORB_SERVER::gyroscope_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ORB_SERVER::gyroscope_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ORB_SERVER

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ORB_SERVER::gyroscope_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ORB_SERVER::gyroscope_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ORB_SERVER::gyroscope_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6761d1eb1d5de5bf0f1edaa1fc9caa02";
  }

  static const char* value(const  ::ORB_SERVER::gyroscope_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6761d1eb1d5de5bfULL;
  static const uint64_t static_value2 = 0x0f1edaa1fc9caa02ULL;
};

template<class ContainerAllocator>
struct DataType< ::ORB_SERVER::gyroscope_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ORB_SERVER/gyroscope";
  }

  static const char* value(const  ::ORB_SERVER::gyroscope_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ORB_SERVER::gyroscope_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 gyrx\n\
float64 gyry\n\
float64 gyrz\n\
\n\
";
  }

  static const char* value(const  ::ORB_SERVER::gyroscope_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ORB_SERVER::gyroscope_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ORB_SERVER::gyroscope_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.gyrx);
    stream.next(m.gyry);
    stream.next(m.gyrz);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct gyroscope_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ORB_SERVER::gyroscope_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ORB_SERVER::gyroscope_<ContainerAllocator> & v) 
  {
    s << indent << "gyrx: ";
    Printer<double>::stream(s, indent + "  ", v.gyrx);
    s << indent << "gyry: ";
    Printer<double>::stream(s, indent + "  ", v.gyry);
    s << indent << "gyrz: ";
    Printer<double>::stream(s, indent + "  ", v.gyrz);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORB_SERVER_MESSAGE_GYROSCOPE_H

